fourcolors=linspecer(4);
morecolors=linspecer(10);

IDENTIFIERSTOPLOT = {...
    {'WT_plasmids_pbla-CRP_pCRP-GFP_asc852'},...
    {'WT_plasmids_pbla-CRP_ps70-GFP_asc853'}};
COLORSWITHIDENTIFIERS = {...
    fourcolors(1,:),...
    fourcolors(1,:),};

CUSTOMLIMITSPERPARAMGROUP = {...
    [NaN NaN    NaN NaN],...
    [0,  6e4    NaN NaN],...
    [NaN NaN    NaN NaN]...
    };
    % {[xlim(1) xlim(2) ylim(1) ylim(2)], ...}

CUSTOMLIMITSPERPARAMGROUPCCS= {...
    [NaN NaN    -.4 .4],...
    [NaN NaN    NaN NaN],...
    [NaN NaN    NaN NaN],...
    [NaN NaN    NaN NaN],...
    [NaN NaN    NaN NaN],...
    [NaN NaN    NaN NaN]...
    };