% The following is defined here:
% GROUPNAME
% IDENTIFIERSTOPLOT
% COLORSWITHIDENTIFIERS
% CUSTOMLIMITSPERPARAMGROUP
% CUSTOMLIMITSPERPARAMGROUPCCS

%{
% Available identifiers in the ribo datasets
{'PrrnaMCerulean_pn25MVenus',...
...
'giu_asc1058_M9_steady',...
'giu_asc1058_M9_steady_antibiotics',...
...
'giu_asc976_TY_steady',...
'giu_asc976_TY_steady_antibiotics',...
'giu_asc976_M9_steady',...
'giu_asc976_M9_steady_antibiotics',...
...
'giu_asc968_M9_steady',...
'giu_asc968_M9_steady_antibiotics'}

%}

GROUPNAME='riboM9steady';

HUMANREADABLENAMESFORGROUPS = ...
    {...
    'Prrna-mCerulean',...
    'L9-mCherry, S2-Venus',...
    'L19-mCerulean',...  
    };

% The plasmid datasets
% { {identifier1}, {identifier2, identifier3}, .. }
% The cells within the cells allow for synonyms, e.g.
% {identifier2,identifier3} will be considered as if they were the
% same identifier.
IDENTIFIERSTOPLOT = {...
    {'mw_asc976_PrrnaMCerulean_pn25MVenus','giu_asc976_M9_steady'},...
{'giu_asc1058_M9_steady'},...
{'giu_asc968_M9_steady'}...
};

% Now also define the colors for these plots
fourcolors=linspecer(4);
morecolors=linspecer(10);
COLORSWITHIDENTIFIERS = {...
    fourcolors(1,:), ... {'WT_plasmids_ps70-GFP_asc841'}, ...
    fourcolors(1,:), ... {'WT_plasmids_pCRP-GFP_asc842'}, ...    
    fourcolors(1,:), ... {'WT_plasmids_pbla-CRP_pCRP-GFP_asc852'}, ...
    fourcolors(1,:), ... {'WT_plasmids_pbla-CRP_ps70-GFP_asc853'}, ...
    fourcolors(2,:), ... {'dCRP_plasmids_pbla-CRP_pCRP-GFP_asc854'}, ...
    fourcolors(2,:), ... {'dCRP_plasmids_pbla-CRP_ps70-GFP_asc855'}, ...
    ...fourcolors(2,:), ... {'dcAMP-extracell800-pCRP-GFP_asc893','dcAMP-extracell800-pCRP-GFP_asc894'},...
    ...fourcolors(2,:), ... {'dcAMP-extracell800-ps70-GFP_asc941'},...
    ...
};
CUSTOMLIMITSPERPARAMGROUP = {...
    [NaN NaN    NaN NaN],... 0   2],...
    [NaN NaN    NaN NaN],... 0,  6e4
    [NaN NaN    NaN NaN]...
    };
    % {[xlim(1) xlim(2) ylim(1) ylim(2)], ...}

CUSTOMLIMITSPERPARAMGROUPCCS= {...
    [NaN NaN    -.4 .4],... [-10 10    -.4 .4],...
    [NaN NaN    NaN NaN],...
    [NaN NaN    NaN NaN],...
    [NaN NaN    NaN NaN],...
    [NaN NaN    NaN NaN],...
    [NaN NaN    NaN NaN]...
    };